# Generated by Django 5.1.4 on 2024-12-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField()),
                ('time_played', models.CharField(max_length=255)),
                ('number_of_mistakes', models.IntegerField()),
            ],
        ),
    ]
