# Generated by Django 5.1.4 on 2024-12-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBoard',
            fields=[
                ('game_number', models.AutoField(primary_key=True, serialize=False)),
                ('time_played', models.CharField(max_length=255)),
                ('number_of_mistakes', models.IntegerField()),
            ],
        ),
    ]
