# Generated by Django 5.1.4 on 2024-12-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboard',
            name='game_number',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='checkboard',
            name='number_of_mistakes',
            field=models.IntegerField(max_length=30),
        ),
    ]
