# Generated by Django 5.1.4 on 2024-12-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_board', '0002_alter_checkboard_game_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboard',
            name='game_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checkboard',
            name='number_of_mistakes',
            field=models.IntegerField(),
        ),
    ]
